### ISSUE TITLE
Missing phpunit patches

### ISSUE THREAD

**Issue by smustgrave** [predis/predis#662] opened 2020-09-18 14:57 UTC
Running composer update always generates
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:234
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:234
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php7.patch" file could not be downloaded: failed to open stream: No such file or directory
    ./tests/phpunit_php8.patch (Fix PHP 8 compatibility)
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:234
Deprecation Notice: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /app/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:234
   Could not apply patch! Skipping. The error was: The "./tests/phpunit_php8.patch" file could not be downloaded: failed to open stream: No such file or directory

Should remove those patches.

**Comment by tillkruss** [comment] 2020-09-18 22:02
Duplicate of #660.

**Closed by tillkruss** 2020-09-18 22:02 UTC
Labels: bug
