### ISSUE TITLE
exists command breaks with tr_TR.utf8 locale

### ISSUE THREAD

**Issue by coffeerocket** [predis/predis#488] opened 2018-02-19 12:24 UTC
The library uses the method strtoupper to capitalize the command.
In the case of the Turkish locale, the "i" is not capitalized, cause it is a special character in Turkish.
The command cannot be found which leads to an error.

**Comment by nrk** [comment] 2020-08-15 13:22
I'm closing this issue as this is a duplicate of #372.

**Closed by nrk** 2020-08-15 13:22 UTC
